export const employeeList = [
  {
    id: 1,
    name: "Alice Johnson",
    empId: "EMP001",
    joiningDate: "2022-03-15",
    role: "Frontend Developer",
    status: "Active",
    exp: "3 years",
    address: "123 Main Street, Springfield",
    email: "difdr@gmail.com",
    department: "HR",
  },
  {
    id: 2,
    name: "Michael Smith",
    empId: "EMP002",
    joiningDate: "2021-11-20",
    role: "Backend Engineer",
    status: "Probation",
    exp: "1 year",
    address: "456 Pine Avenue, Metropolis",
    department: "HR",
  },
  {
    id: 3,
    name: "Priya Kumar",
    empId: "EMP003",
    joiningDate: "2019-07-05",
    role: "Project Manager",
    status: "Active",
    exp: "5 years",
    address: "789 Oak Road, Newtown",
    department: "HR",
  },
  {
    id: 4,
    name: "David Lee",
    empId: "EMP004",
    joiningDate: "2023-01-10",
    role: "UI/UX Designer",
    status: "Active",
    exp: "2 years",
    address: "101 River Street, Oldtown",
    department: "HR",
  },
];


